/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gnee_window (void)
{
  GtkWidget *gnee_window;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem3;
  GtkWidget *menuitem3_menu;
  GtkWidget *log_window;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *hbox9;
  GtkWidget *file_toolbar;
  GtkWidget *new_button;
  GtkWidget *open_button;
  GtkWidget *save_button;
  GtkWidget *action_toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *record_button;
  GtkWidget *replay_button;
  GtkWidget *stop_button;
  GtkWidget *notebook;
  GtkWidget *general_settings_box;
  GtkWidget *time_settings_box;
  GtkWidget *label11;
  GtkWidget *timeout_box;
  GtkWidget *wait_checkbox;
  GtkObject *wait_spinbutton_adj;
  GtkWidget *wait_spinbutton;
  GtkWidget *log_settings_box;
  GtkWidget *label14;
  GtkWidget *verbose_logging_box;
  GtkWidget *verbose_logging_checkbox;
  GtkWidget *distribution_settings_box;
  GtkWidget *label13;
  GtkWidget *distribution_list_box;
  GtkWidget *vbox4;
  GtkWidget *hbox6;
  GtkWidget *label8;
  GtkWidget *distribute_display_entry;
  GtkWidget *scrolledwindow3;
  GtkWidget *distribution_list_view;
  GtkWidget *vbuttonbox1;
  GtkWidget *add_to_distribution_list_butotn;
  GtkWidget *remove_from_distribution_list_button;
  GtkWidget *hbox12;
  GtkWidget *distribute_when_recording_checkbox;
  GtkWidget *label6;
  GtkWidget *record_settings_box;
  GtkWidget *vbox5;
  GtkWidget *label19;
  GtkWidget *record_display_box;
  GtkWidget *checkbutton7;
  GtkWidget *entry3;
  GtkWidget *vbox8;
  GtkWidget *label21;
  GtkWidget *record_clients_box;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *vbox6;
  GtkWidget *label20;
  GtkWidget *record_recordables_box;
  GtkWidget *hbox3;
  GtkWidget *event_group_combo;
  GtkWidget *combo_label1;
  GtkWidget *recordable_listview_box;
  GtkWidget *vbox10;
  GtkWidget *label22;
  GtkWidget *scrolledwindow4;
  GtkWidget *exclude_list;
  GtkWidget *vbuttonbox2;
  GtkWidget *record_include_button;
  GtkWidget *image3;
  GtkWidget *record_exclude_button;
  GtkWidget *image2;
  GtkWidget *vbox11;
  GtkWidget *label23;
  GtkWidget *scrolledwindow5;
  GtkWidget *include_list;
  GtkWidget *label1;
  GtkWidget *replay_settings_box;
  GtkWidget *replay_display_box;
  GtkWidget *label15;
  GtkWidget *hbox13;
  GtkWidget *checkbutton5;
  GtkWidget *entry2;
  GtkWidget *replay_speed_box;
  GtkWidget *label17;
  GtkWidget *hbox14;
  GtkWidget *checkbutton4;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *replay_error_handling_box;
  GtkWidget *label18;
  GtkWidget *checkbutton6;
  GtkWidget *vbox12;
  GtkWidget *label24;
  GtkWidget *replay_files_box;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview3;
  GtkWidget *vbuttonbox3;
  GtkWidget *button3;
  GtkWidget *label2;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  gnee_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gnee_window), _("Gnee"));
  gtk_window_set_default_size (GTK_WINDOW (gnee_window), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gnee_window), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_as1);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem3_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menuitem3_menu);

  log_window = gtk_check_menu_item_new_with_mnemonic (_("_Log window"));
  gtk_widget_show (log_window);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), log_window);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox9, FALSE, TRUE, 0);

  file_toolbar = gtk_toolbar_new ();
  gtk_widget_show (file_toolbar);
  gtk_box_pack_start (GTK_BOX (hbox9), file_toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (file_toolbar), GTK_TOOLBAR_BOTH);

  new_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (file_toolbar),
                                "gtk-new",
                                "gtk-new",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (new_button);

  open_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (file_toolbar),
                                "gtk-open",
                                "gtk-open",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (open_button);

  save_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (file_toolbar),
                                "gtk-save",
                                "gtk-save",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (save_button);

  action_toolbar = gtk_toolbar_new ();
  gtk_widget_show (action_toolbar);
  gtk_box_pack_start (GTK_BOX (hbox9), action_toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (action_toolbar), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-no", gtk_toolbar_get_icon_size (GTK_TOOLBAR (action_toolbar)));
  record_button = gtk_toolbar_append_element (GTK_TOOLBAR (action_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Record"),
                                _("Record"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (action_toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (record_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-yes", gtk_toolbar_get_icon_size (GTK_TOOLBAR (action_toolbar)));
  replay_button = gtk_toolbar_append_element (GTK_TOOLBAR (action_toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Replay"),
                                _("Replay"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (action_toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (replay_button);

  stop_button = gtk_toolbar_insert_stock (GTK_TOOLBAR (action_toolbar),
                                "gtk-stop",
                                "gtk-stop",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (stop_button);
  gtk_widget_set_sensitive (stop_button, FALSE);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook), 4);

  general_settings_box = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (general_settings_box);
  gtk_container_add (GTK_CONTAINER (notebook), general_settings_box);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook), general_settings_box,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (general_settings_box), 4);

  time_settings_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (time_settings_box);
  gtk_box_pack_start (GTK_BOX (general_settings_box), time_settings_box, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("<b>Timing</b>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (time_settings_box), label11, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  timeout_box = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (timeout_box);
  gtk_box_pack_start (GTK_BOX (time_settings_box), timeout_box, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (timeout_box), 4);

  wait_checkbox = gtk_check_button_new_with_mnemonic (_("Seconds to wait before starting to record/replay"));
  gtk_widget_show (wait_checkbox);
  gtk_box_pack_start (GTK_BOX (timeout_box), wait_checkbox, FALSE, FALSE, 0);

  wait_spinbutton_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  wait_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (wait_spinbutton_adj), 1, 0);
  gtk_widget_show (wait_spinbutton);
  gtk_box_pack_start (GTK_BOX (timeout_box), wait_spinbutton, FALSE, FALSE, 0);

  log_settings_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (log_settings_box);
  gtk_box_pack_start (GTK_BOX (general_settings_box), log_settings_box, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("<b>Logging</b>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (log_settings_box), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0);

  verbose_logging_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (verbose_logging_box);
  gtk_box_pack_start (GTK_BOX (log_settings_box), verbose_logging_box, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (verbose_logging_box), 4);

  verbose_logging_checkbox = gtk_check_button_new_with_mnemonic (_("Verbose logging"));
  gtk_widget_show (verbose_logging_checkbox);
  gtk_box_pack_start (GTK_BOX (verbose_logging_box), verbose_logging_checkbox, FALSE, FALSE, 0);

  distribution_settings_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (distribution_settings_box);
  gtk_box_pack_start (GTK_BOX (general_settings_box), distribution_settings_box, TRUE, TRUE, 0);

  label13 = gtk_label_new (_("<b>Distribution</b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (distribution_settings_box), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0);

  distribution_list_box = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (distribution_list_box);
  gtk_box_pack_start (GTK_BOX (distribution_settings_box), distribution_list_box, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (distribution_list_box), 4);

  vbox4 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (distribution_list_box), vbox4, TRUE, TRUE, 4);

  hbox6 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox6), 2);

  label8 = gtk_label_new (_("Distribute to display:"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  distribute_display_entry = gtk_entry_new ();
  gtk_widget_show (distribute_display_entry);
  gtk_box_pack_start (GTK_BOX (hbox6), distribute_display_entry, TRUE, TRUE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  distribution_list_view = gtk_tree_view_new ();
  gtk_widget_show (distribution_list_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), distribution_list_view);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (distribution_list_view), FALSE);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (distribution_list_box), vbuttonbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbuttonbox1), 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox1), GTK_BUTTONBOX_START);

  add_to_distribution_list_butotn = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (add_to_distribution_list_butotn);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), add_to_distribution_list_butotn);
  GTK_WIDGET_SET_FLAGS (add_to_distribution_list_butotn, GTK_CAN_DEFAULT);

  remove_from_distribution_list_button = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_show (remove_from_distribution_list_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), remove_from_distribution_list_button);
  GTK_WIDGET_SET_FLAGS (remove_from_distribution_list_button, GTK_CAN_DEFAULT);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (distribution_settings_box), hbox12, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox12), 4);

  distribute_when_recording_checkbox = gtk_check_button_new_with_mnemonic (_("Distribute when recording"));
  gtk_widget_show (distribute_when_recording_checkbox);
  gtk_box_pack_start (GTK_BOX (hbox12), distribute_when_recording_checkbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (distribute_when_recording_checkbox), 4);

  label6 = gtk_label_new (_("General settings"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label6);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  record_settings_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (record_settings_box);
  gtk_container_add (GTK_CONTAINER (notebook), record_settings_box);
  gtk_container_set_border_width (GTK_CONTAINER (record_settings_box), 4);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (record_settings_box), vbox5, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 4);

  label19 = gtk_label_new (_("<b>Display</b>"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (vbox5), label19, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0);

  record_display_box = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (record_display_box);
  gtk_box_pack_start (GTK_BOX (vbox5), record_display_box, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (record_display_box), 4);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("Record from display: "));
  gtk_widget_show (checkbutton7);
  gtk_box_pack_start (GTK_BOX (record_display_box), checkbutton7, FALSE, FALSE, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (record_display_box), entry3, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (record_settings_box), vbox8, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 4);

  label21 = gtk_label_new (_("<b>Clients</b>"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (vbox8), label21, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0);

  record_clients_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (record_clients_box);
  gtk_box_pack_start (GTK_BOX (vbox8), record_clients_box, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (record_clients_box), 4);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Record all clients"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (record_clients_box), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Record only future clients"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (record_clients_box), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (record_settings_box), vbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 4);

  label20 = gtk_label_new (_("<b>Recordables</b>"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (vbox6), label20, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0);

  record_recordables_box = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (record_recordables_box);
  gtk_box_pack_start (GTK_BOX (vbox6), record_recordables_box, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (record_recordables_box), 4);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (record_recordables_box), hbox3, FALSE, FALSE, 0);

  event_group_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (event_group_combo)->popwin),
                     "GladeParentKey", event_group_combo);
  gtk_widget_show (event_group_combo);
  gtk_box_pack_start (GTK_BOX (hbox3), event_group_combo, TRUE, TRUE, 0);

  combo_label1 = GTK_COMBO (event_group_combo)->entry;
  gtk_widget_show (combo_label1);
  gtk_editable_set_editable (GTK_EDITABLE (combo_label1), FALSE);

  recordable_listview_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (recordable_listview_box);
  gtk_box_pack_start (GTK_BOX (record_recordables_box), recordable_listview_box, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (recordable_listview_box), vbox10, TRUE, TRUE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Exclude:"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (vbox10), label22, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox10), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  exclude_list = gtk_tree_view_new ();
  gtk_widget_show (exclude_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), exclude_list);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (exclude_list), FALSE);

  vbuttonbox2 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox2);
  gtk_box_pack_start (GTK_BOX (recordable_listview_box), vbuttonbox2, FALSE, FALSE, 16);
  gtk_container_set_border_width (GTK_CONTAINER (vbuttonbox2), 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox2), GTK_BUTTONBOX_END);

  record_include_button = gtk_button_new ();
  gtk_widget_show (record_include_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), record_include_button);
  GTK_WIDGET_SET_FLAGS (record_include_button, GTK_CAN_DEFAULT);

  image3 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (record_include_button), image3);

  record_exclude_button = gtk_button_new ();
  gtk_widget_show (record_exclude_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox2), record_exclude_button);
  GTK_WIDGET_SET_FLAGS (record_exclude_button, GTK_CAN_DEFAULT);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (record_exclude_button), image2);

  vbox11 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (recordable_listview_box), vbox11, TRUE, TRUE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Include:"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox11), label23, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox11), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  include_list = gtk_tree_view_new ();
  gtk_widget_show (include_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), include_list);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (include_list), FALSE);

  label1 = gtk_label_new (_("Record settings"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  replay_settings_box = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (replay_settings_box);
  gtk_container_add (GTK_CONTAINER (notebook), replay_settings_box);
  gtk_container_set_border_width (GTK_CONTAINER (replay_settings_box), 4);

  replay_display_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (replay_display_box);
  gtk_box_pack_start (GTK_BOX (replay_settings_box), replay_display_box, FALSE, FALSE, 0);

  label15 = gtk_label_new (_("<b>Display</b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (replay_display_box), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0);

  hbox13 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (replay_display_box), hbox13, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox13), 4);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("Replay on display:"));
  gtk_widget_show (checkbutton5);
  gtk_box_pack_start (GTK_BOX (hbox13), checkbutton5, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton5, _("Enables replay on a different display (default localhost:0)"), NULL);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (hbox13), entry2, TRUE, TRUE, 0);

  replay_speed_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (replay_speed_box);
  gtk_box_pack_start (GTK_BOX (replay_settings_box), replay_speed_box, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("<b>Speed</b>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (replay_speed_box), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0);

  hbox14 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (replay_speed_box), hbox14, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox14), 4);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Replay with speed:"));
  gtk_widget_show (checkbutton4);
  gtk_box_pack_start (GTK_BOX (hbox14), checkbutton4, FALSE, FALSE, 0);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_box_pack_start (GTK_BOX (hbox14), spinbutton3, TRUE, TRUE, 0);

  replay_error_handling_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (replay_error_handling_box);
  gtk_box_pack_start (GTK_BOX (replay_settings_box), replay_error_handling_box, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("<b>Error handling</b>"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (replay_error_handling_box), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("Force replay even when not synchronized"));
  gtk_widget_show (checkbutton6);
  gtk_box_pack_start (GTK_BOX (replay_error_handling_box), checkbutton6, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton6), 4);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (replay_settings_box), vbox12, TRUE, TRUE, 0);

  label24 = gtk_label_new (_("<b>Replay file</b>"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox12), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0);

  replay_files_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (replay_files_box);
  gtk_box_pack_start (GTK_BOX (vbox12), replay_files_box, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (replay_files_box), 4);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (replay_files_box), scrolledwindow6, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_SHADOW_IN);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview3);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview3), FALSE);

  vbuttonbox3 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox3);
  gtk_box_pack_start (GTK_BOX (replay_files_box), vbuttonbox3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbuttonbox3), 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox3), GTK_BUTTONBOX_START);

  button3 = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (vbuttonbox3), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  label2 = gtk_label_new (_("Replay settings"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label2);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  g_signal_connect_swapped ((gpointer) gnee_window, "hide",
                            G_CALLBACK (on_gnee_window_hide),
                            GTK_OBJECT (gnee_window));
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) log_window, "activate",
                    G_CALLBACK (on_log_window_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect_swapped ((gpointer) record_button, "clicked",
                            G_CALLBACK (on_record),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) replay_button, "clicked",
                            G_CALLBACK (on_replay),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) combo_label1, "changed",
                            G_CALLBACK (on_combo_label1_changed),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) exclude_list, "row_activated",
                            G_CALLBACK (on_exclude_list_row_activated),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) record_include_button, "clicked",
                            G_CALLBACK (on_record_include_button_clicked),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) record_exclude_button, "clicked",
                            G_CALLBACK (on_record_exclude_button_clicked),
                            GTK_OBJECT (gnee_window));
  g_signal_connect_swapped ((gpointer) include_list, "row_activated",
                            G_CALLBACK (on_include_list_row_activated),
                            GTK_OBJECT (gnee_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gnee_window, gnee_window, "gnee_window");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gnee_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (gnee_window, new1, "new1");
  GLADE_HOOKUP_OBJECT (gnee_window, open1, "open1");
  GLADE_HOOKUP_OBJECT (gnee_window, save1, "save1");
  GLADE_HOOKUP_OBJECT (gnee_window, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (gnee_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gnee_window, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem3_menu, "menuitem3_menu");
  GLADE_HOOKUP_OBJECT (gnee_window, log_window, "log_window");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (gnee_window, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (gnee_window, about1, "about1");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gnee_window, file_toolbar, "file_toolbar");
  GLADE_HOOKUP_OBJECT (gnee_window, new_button, "new_button");
  GLADE_HOOKUP_OBJECT (gnee_window, open_button, "open_button");
  GLADE_HOOKUP_OBJECT (gnee_window, save_button, "save_button");
  GLADE_HOOKUP_OBJECT (gnee_window, action_toolbar, "action_toolbar");
  GLADE_HOOKUP_OBJECT (gnee_window, record_button, "record_button");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_button, "replay_button");
  GLADE_HOOKUP_OBJECT (gnee_window, stop_button, "stop_button");
  GLADE_HOOKUP_OBJECT (gnee_window, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (gnee_window, general_settings_box, "general_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, time_settings_box, "time_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label11, "label11");
  GLADE_HOOKUP_OBJECT (gnee_window, timeout_box, "timeout_box");
  GLADE_HOOKUP_OBJECT (gnee_window, wait_checkbox, "wait_checkbox");
  GLADE_HOOKUP_OBJECT (gnee_window, wait_spinbutton, "wait_spinbutton");
  GLADE_HOOKUP_OBJECT (gnee_window, log_settings_box, "log_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label14, "label14");
  GLADE_HOOKUP_OBJECT (gnee_window, verbose_logging_box, "verbose_logging_box");
  GLADE_HOOKUP_OBJECT (gnee_window, verbose_logging_checkbox, "verbose_logging_checkbox");
  GLADE_HOOKUP_OBJECT (gnee_window, distribution_settings_box, "distribution_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label13, "label13");
  GLADE_HOOKUP_OBJECT (gnee_window, distribution_list_box, "distribution_list_box");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gnee_window, label8, "label8");
  GLADE_HOOKUP_OBJECT (gnee_window, distribute_display_entry, "distribute_display_entry");
  GLADE_HOOKUP_OBJECT (gnee_window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gnee_window, distribution_list_view, "distribution_list_view");
  GLADE_HOOKUP_OBJECT (gnee_window, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (gnee_window, add_to_distribution_list_butotn, "add_to_distribution_list_butotn");
  GLADE_HOOKUP_OBJECT (gnee_window, remove_from_distribution_list_button, "remove_from_distribution_list_button");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (gnee_window, distribute_when_recording_checkbox, "distribute_when_recording_checkbox");
  GLADE_HOOKUP_OBJECT (gnee_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (gnee_window, record_settings_box, "record_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (gnee_window, label19, "label19");
  GLADE_HOOKUP_OBJECT (gnee_window, record_display_box, "record_display_box");
  GLADE_HOOKUP_OBJECT (gnee_window, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (gnee_window, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (gnee_window, label21, "label21");
  GLADE_HOOKUP_OBJECT (gnee_window, record_clients_box, "record_clients_box");
  GLADE_HOOKUP_OBJECT (gnee_window, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (gnee_window, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (gnee_window, label20, "label20");
  GLADE_HOOKUP_OBJECT (gnee_window, record_recordables_box, "record_recordables_box");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gnee_window, event_group_combo, "event_group_combo");
  GLADE_HOOKUP_OBJECT (gnee_window, combo_label1, "combo_label1");
  GLADE_HOOKUP_OBJECT (gnee_window, recordable_listview_box, "recordable_listview_box");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (gnee_window, label22, "label22");
  GLADE_HOOKUP_OBJECT (gnee_window, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (gnee_window, exclude_list, "exclude_list");
  GLADE_HOOKUP_OBJECT (gnee_window, vbuttonbox2, "vbuttonbox2");
  GLADE_HOOKUP_OBJECT (gnee_window, record_include_button, "record_include_button");
  GLADE_HOOKUP_OBJECT (gnee_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (gnee_window, record_exclude_button, "record_exclude_button");
  GLADE_HOOKUP_OBJECT (gnee_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (gnee_window, label23, "label23");
  GLADE_HOOKUP_OBJECT (gnee_window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (gnee_window, include_list, "include_list");
  GLADE_HOOKUP_OBJECT (gnee_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_settings_box, "replay_settings_box");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_display_box, "replay_display_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label15, "label15");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gnee_window, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (gnee_window, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_speed_box, "replay_speed_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (gnee_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gnee_window, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (gnee_window, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_error_handling_box, "replay_error_handling_box");
  GLADE_HOOKUP_OBJECT (gnee_window, label18, "label18");
  GLADE_HOOKUP_OBJECT (gnee_window, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (gnee_window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (gnee_window, label24, "label24");
  GLADE_HOOKUP_OBJECT (gnee_window, replay_files_box, "replay_files_box");
  GLADE_HOOKUP_OBJECT (gnee_window, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (gnee_window, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (gnee_window, vbuttonbox3, "vbuttonbox3");
  GLADE_HOOKUP_OBJECT (gnee_window, button3, "button3");
  GLADE_HOOKUP_OBJECT (gnee_window, label2, "label2");
  GLADE_HOOKUP_OBJECT_NO_REF (gnee_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (gnee_window), accel_group);

  return gnee_window;
}

