\input texinfo  @c -*- Texinfo -*-
@c %**start of header
@setfilename xnee.info
@settitle Xnee Manual
@setchapternewpage off
@c %**end o



@include version.texi


@dircategory Miscellaneous
@direntry
@ * : (Xnee).        Xnee's Not Event Emulator.
@end direntry


@c Put everything in one index (arbitrarily chosen to be the concept index).
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex vr cp

@c This is used by a cross ref in make-stds.texi
@set CODESTD  1
@iftex
@set CHAPTER chapter
@end iftex
@ifinfo
@set CHAPTER node
@end ifinfo




@titlepage
@sp 10
@c omment The title is printed in a large font
@center @titlefont{Xnee Manual}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@title Xnee Manual 
@subtitle Xnee is a suite of programs with,
@subtitle recording, replaying and 'distribution'
@subtitle capabilities for X Window System
@subtitle version @value{VERSION} @value{UPDATED} 
@author Henrik Sandklef
@include xnee_copying
@end titlepage


@ifinfo
@node Top, Summary, (dir), (dir)
@top 
@end ifinfo

@menu
* Summary::              Summary
* Getting started::      Getting started
* Functional overview::  Functional overview
* Installation::         Installation
* Examples::             examples
* File format::          File format
* Programs::             Programs
* Internals::            Internals
* Requirements::         Requirements
* FAQ::                  FAQ
* Copying This Manual::  Copying This Manual
* Index::                Index
@end menu


@shortcontents

@node    Summary, Getting started, top, top
@include xnee_intro.texi
@page

@node    Getting started, Functional overview, Summary, top
@include xnee_start.texi
@page

@node    Functional overview, Installation, Getting started, top
@include xnee_func.texi
@include xnee_general.texi
@page


@node    Installation, Examples, Functional overview, top
@include xnee_install.texi
@page

@node    Examples, Programs, Installation, top
@include xnee_exampl.texi
@page

@node    Programs, File format, Examples, top
@include xnee_progs.texi
@page

@node    File format, Internals, Programs, top
@include xnee_prot.texi
@page

@node    Internals, Requirements, File format, top
@include xnee_intern.texi
@page

@node    Requirements , FAQ, Internals, top
@include xnee_req.texi
@page

@node    FAQ, Copying This Manual, Requirements, top
@include xnee_faq.texi
@page


@node    Copying This Manual, Index, FAQ, top
@appendix Copying This Manual
@include fdl.texi

@node    Index, (dir), Copying This Manual, top
@chapter Index
@printindex cp

@contents

@bye

