\input texinfo  @c -*- Texinfo -*-
@c %**start of header
@setfilename xnee.info
@settitle Xnee Manual
@setchapternewpage off
@c %**end o



@include version.texi


@dircategory Miscellaneous
@direntry
@ * : (Xnee).        Xnee's Not Event Emulator.
@end direntry


@c Put everything in one index (arbitrarily chosen to be the concept index).
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex vr cp

@c This is used by a cross ref in make-stds.texi
@set CODESTD  1
@iftex
@set CHAPTER chapter
@end iftex
@ifinfo
@set CHAPTER node
@end ifinfo




@titlepage
@sp 10
@c omment The title is printed in a large font
@center @titlefont{Xnee Manual}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@title Xnee Manual 
@subtitle Xnee is a suite of programs with,
@subtitle recording, replaying and 'distribution'
@subtitle capabilities for X Window System
@subtitle version @value{VERSION} @value{UPDATED} 
@author Henrik Sandklef
@include xnee_copying
@end titlepage


@ifinfo
@node Top,Introduction,, (dir)
@top 
@include xnee_copying
@end ifinfo


@menu
* Summary::              Summary
* Getting started::      Getting started
* General ideas::        General ideas
* Installation::         Installation
* Examples::             examples
* Usage::                usage
* File format::          File format
* Internals::            Internals
* Requirements::         Requirements
* FAQ::                  FAQ
* Copying This Manual::  Copying This Manual
* Index::                Index
@end menu


@shortcontents

@node Description, Getting started, top, top
@include xnee_intro.texi
@page
@include xnee_start.texi
@page
@chapter Functional overview


@section Functional overview
@cindex Functional overview
The Xnee applications (gnee and xnee) receives X11 protocol data (e.g. events)
from an X server (using libxnee) and print them to a file, called Xnee 
Session File. Theses events are later read from the session file and replayed.
Gnee and xnee can read its settings from a file, called Xnee Project File, 
or from command line (cnee) or via the GUI (gnee).


@*
Events directly generated by the user (e.g KeyPress) can be replayed 
or faked. Requests, replies, errors and events not directly generated by the 
user (e.g MapNotify) can be recorded as well. By using these data  
Xnee can replay with synchronisation. 

@ifnotinfo
This picture gives an overview of Xnee and the files used.
@*
@image{xngener, 10cm}
@end ifnotinfo



@include xnee_general.texi
@page
@include xnee_install.texi
@page
@include xnee_exampl.texi
@page
@include xnee_prot.texi
@page
@include xnee_intern.texi
@page
@include xnee_req.texi
@page
@node FAQ, Copying This Manual, Requirements, top
@include xnee_faq.texi


@node Copying This Manual, Index, FAQ, top
@appendix Copying This Manual

@include fdl.texi

@node Index, (dir), Copying This Manual, top
@chapter Index
@printindex cp

@contents

@bye

