/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_pnee_pref (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_pnee_about (void);
GtkWidget* create_pnee_panel (void);
