/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_pnee_pref (void)
{
  GtkWidget *pnee_pref;
  GtkWidget *main_notebook;
  GtkWidget *vbox1;
  GtkWidget *general_frame;
  GtkWidget *alignment5;
  GtkWidget *table1;
  GtkWidget *verbose_check;
  GtkWidget *hbox9;
  GtkWidget *delay_check;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *general_label;
  GtkWidget *record_frame;
  GtkWidget *alignment4;
  GtkWidget *vbox4;
  GtkWidget *hbox4;
  GtkWidget *rec_file_label;
  GtkWidget *entry3;
  GtkWidget *rec_file_button;
  GtkWidget *hbox11;
  GtkWidget *hbox10;
  GtkWidget *nr_events_label;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *hbox11b;
  GtkWidget *grab_label;
  GtkWidget *entry5;
  GtkWidget *record_label;
  GtkWidget *replay_frame;
  GtkWidget *alignment2;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *repl_file_label;
  GtkWidget *rep_choose_but;
  GtkWidget *hbox5;
  GtkWidget *speed_check;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *replay_label;
  GtkWidget *setting_ok;
  GtkWidget *settings_label;
  GtkWidget *vbox5;
  GtkWidget *faked_rec;
  GtkWidget *faked_rep;
  GtkWidget *about_label;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  pnee_pref = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (pnee_pref), "Pnee - Preferences");

  main_notebook = gtk_notebook_new ();
  gtk_widget_show (main_notebook);
  gtk_container_add (GTK_CONTAINER (pnee_pref), main_notebook);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox1);

  general_frame = gtk_frame_new (NULL);
  gtk_widget_show (general_frame);
  gtk_box_pack_start (GTK_BOX (vbox1), general_frame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (general_frame), GTK_SHADOW_NONE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (general_frame), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment5), table1);

  verbose_check = gtk_check_button_new_with_mnemonic ("verbose logging");
  gtk_widget_show (verbose_check);
  gtk_table_attach (GTK_TABLE (table1), verbose_check, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_table_attach (GTK_TABLE (table1), hbox9, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  delay_check = gtk_check_button_new_with_mnemonic ("Delay");
  gtk_widget_show (delay_check);
  gtk_box_pack_start (GTK_BOX (hbox9), delay_check, FALSE, FALSE, 0);

  spinbutton2_adj = gtk_adjustment_new (3, 0, 10000, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_box_pack_start (GTK_BOX (hbox9), spinbutton2, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton2, "Delay start of record or replay. (seconds)", NULL);

  general_label = gtk_label_new ("<b>General</b>");
  gtk_widget_show (general_label);
  gtk_frame_set_label_widget (GTK_FRAME (general_frame), general_label);
  gtk_label_set_use_markup (GTK_LABEL (general_label), TRUE);

  record_frame = gtk_frame_new (NULL);
  gtk_widget_show (record_frame);
  gtk_box_pack_start (GTK_BOX (vbox1), record_frame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (record_frame), GTK_SHADOW_NONE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (record_frame), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), vbox4);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox4, TRUE, TRUE, 0);

  rec_file_label = gtk_label_new ("Record to file");
  gtk_widget_show (rec_file_label);
  gtk_box_pack_start (GTK_BOX (hbox4), rec_file_label, FALSE, FALSE, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (hbox4), entry3, TRUE, TRUE, 0);

  rec_file_button = gtk_button_new_with_mnemonic ("...");
  gtk_widget_show (rec_file_button);
  gtk_box_pack_start (GTK_BOX (hbox4), rec_file_button, FALSE, FALSE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox11, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (hbox11), hbox10, TRUE, TRUE, 0);

  nr_events_label = gtk_label_new ("Events to record");
  gtk_widget_show (nr_events_label);
  gtk_box_pack_start (GTK_BOX (hbox10), nr_events_label, FALSE, FALSE, 0);

  spinbutton3_adj = gtk_adjustment_new (200, -1, 10000, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_box_pack_start (GTK_BOX (hbox10), spinbutton3, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton3, "Number of events to record (-1 for ever).", NULL);

  hbox11b = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11b);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox11b, TRUE, TRUE, 0);

  grab_label = gtk_label_new ("Stop key");
  gtk_widget_show (grab_label);
  gtk_box_pack_start (GTK_BOX (hbox11b), grab_label, FALSE, FALSE, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox11b), entry5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry5, 4, -1);
  gtk_tooltips_set_tip (tooltips, entry5, "Grab a key to stop recording", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry5), 5);
  gtk_entry_set_text (GTK_ENTRY (entry5), "F1");

  record_label = gtk_label_new ("<b>Record</b>");
  gtk_widget_show (record_label);
  gtk_frame_set_label_widget (GTK_FRAME (record_frame), record_label);
  gtk_label_set_use_markup (GTK_LABEL (record_label), TRUE);

  replay_frame = gtk_frame_new (NULL);
  gtk_widget_show (replay_frame);
  gtk_box_pack_start (GTK_BOX (vbox1), replay_frame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (replay_frame), GTK_SHADOW_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (replay_frame), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);

  repl_file_label = gtk_label_new ("Replay from file");
  gtk_widget_show (repl_file_label);
  gtk_box_pack_start (GTK_BOX (hbox3), repl_file_label, FALSE, FALSE, 0);

  rep_choose_but = gtk_file_chooser_button_new ("Select A File", GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (rep_choose_but);
  gtk_box_pack_start (GTK_BOX (hbox3), rep_choose_but, TRUE, TRUE, 0);
  g_object_set (rep_choose_but,
                "local-only", FALSE,
                NULL);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox5, TRUE, TRUE, 0);

  speed_check = gtk_check_button_new_with_mnemonic ("Replay speed %");
  gtk_widget_show (speed_check);
  gtk_box_pack_start (GTK_BOX (hbox5), speed_check, FALSE, FALSE, 0);

  spinbutton1_adj = gtk_adjustment_new (100, 1, 10000, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox5), spinbutton1, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton1, "Set a different speed", NULL);

  replay_label = gtk_label_new ("<b>Replay</b>");
  gtk_widget_show (replay_label);
  gtk_frame_set_label_widget (GTK_FRAME (replay_frame), replay_label);
  gtk_label_set_use_markup (GTK_LABEL (replay_label), TRUE);

  setting_ok = gtk_button_new_with_mnemonic ("OK");
  gtk_widget_show (setting_ok);
  gtk_box_pack_start (GTK_BOX (vbox1), setting_ok, FALSE, FALSE, 0);

  settings_label = gtk_label_new ("Settings");
  gtk_widget_show (settings_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 0), settings_label);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox5);

  faked_rec = gtk_button_new_with_mnemonic ("Record");
  gtk_widget_show (faked_rec);
  gtk_box_pack_start (GTK_BOX (vbox5), faked_rec, FALSE, FALSE, 0);

  faked_rep = gtk_button_new_with_mnemonic ("Replay");
  gtk_widget_show (faked_rep);
  gtk_box_pack_start (GTK_BOX (vbox5), faked_rep, FALSE, FALSE, 0);

  about_label = gtk_label_new ("About");
  gtk_widget_show (about_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 1), about_label);

  g_signal_connect_swapped ((gpointer) verbose_check, "toggled",
                            G_CALLBACK (on_verbose_check_toggled),
                            GTK_OBJECT (verbose_check));
  g_signal_connect_swapped ((gpointer) delay_check, "toggled",
                            G_CALLBACK (on_delay_check_toggled),
                            GTK_OBJECT (delay_check));
  g_signal_connect_swapped ((gpointer) spinbutton2, "value_changed",
                            G_CALLBACK (on_spinbutton2_change_value),
                            GTK_OBJECT (spinbutton2));
  g_signal_connect_swapped ((gpointer) rec_file_button, "clicked",
                            G_CALLBACK (on_rec_file_button_clicked),
                            GTK_OBJECT (rec_file_button));
  g_signal_connect_swapped ((gpointer) spinbutton3, "value_changed",
                            G_CALLBACK (on_spinbutton3_value_changed),
                            GTK_OBJECT (spinbutton3));
  g_signal_connect_swapped ((gpointer) entry5, "changed",
                            G_CALLBACK (on_entry5_changed),
                            GTK_OBJECT (entry5));
  g_signal_connect_swapped ((gpointer) rep_choose_but, "file_activated",
                            G_CALLBACK (on_rep_choose_but_file_activated),
                            GTK_OBJECT (rep_choose_but));
  g_signal_connect_swapped ((gpointer) rep_choose_but, "selection_changed",
                            G_CALLBACK (on_rep_choose_but_file_activated),
                            GTK_OBJECT (rep_choose_but));
  g_signal_connect_swapped ((gpointer) speed_check, "toggled",
                            G_CALLBACK (on_speed_check_toggled),
                            GTK_OBJECT (speed_check));
  g_signal_connect_swapped ((gpointer) spinbutton1, "value_changed",
                            G_CALLBACK (on_spinbutton1_value_changed),
                            GTK_OBJECT (spinbutton1));
  g_signal_connect_swapped ((gpointer) setting_ok, "clicked",
                            G_CALLBACK (on_setting_ok_clicked),
                            GTK_OBJECT (pnee_pref));
  g_signal_connect_swapped ((gpointer) faked_rec, "clicked",
                            G_CALLBACK (on_faked_rec_clicked),
                            GTK_OBJECT (faked_rec));
  g_signal_connect_swapped ((gpointer) faked_rep, "clicked",
                            G_CALLBACK (on_faked_rep_clicked),
                            GTK_OBJECT (faked_rep));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pnee_pref, pnee_pref, "pnee_pref");
  GLADE_HOOKUP_OBJECT (pnee_pref, main_notebook, "main_notebook");
  GLADE_HOOKUP_OBJECT (pnee_pref, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (pnee_pref, general_frame, "general_frame");
  GLADE_HOOKUP_OBJECT (pnee_pref, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (pnee_pref, table1, "table1");
  GLADE_HOOKUP_OBJECT (pnee_pref, verbose_check, "verbose_check");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (pnee_pref, delay_check, "delay_check");
  GLADE_HOOKUP_OBJECT (pnee_pref, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (pnee_pref, general_label, "general_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, record_frame, "record_frame");
  GLADE_HOOKUP_OBJECT (pnee_pref, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (pnee_pref, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (pnee_pref, rec_file_label, "rec_file_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (pnee_pref, rec_file_button, "rec_file_button");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (pnee_pref, nr_events_label, "nr_events_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox11b, "hbox11b");
  GLADE_HOOKUP_OBJECT (pnee_pref, grab_label, "grab_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (pnee_pref, record_label, "record_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, replay_frame, "replay_frame");
  GLADE_HOOKUP_OBJECT (pnee_pref, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (pnee_pref, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (pnee_pref, repl_file_label, "repl_file_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, rep_choose_but, "rep_choose_but");
  GLADE_HOOKUP_OBJECT (pnee_pref, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (pnee_pref, speed_check, "speed_check");
  GLADE_HOOKUP_OBJECT (pnee_pref, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (pnee_pref, replay_label, "replay_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, setting_ok, "setting_ok");
  GLADE_HOOKUP_OBJECT (pnee_pref, settings_label, "settings_label");
  GLADE_HOOKUP_OBJECT (pnee_pref, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (pnee_pref, faked_rec, "faked_rec");
  GLADE_HOOKUP_OBJECT (pnee_pref, faked_rep, "faked_rep");
  GLADE_HOOKUP_OBJECT (pnee_pref, about_label, "about_label");
  GLADE_HOOKUP_OBJECT_NO_REF (pnee_pref, tooltips, "tooltips");

  return pnee_pref;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *f_c_button;
  GtkWidget *f_open_button;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  g_object_set (filechooserdialog1,
                "local-only", FALSE,
                "show-hidden", TRUE,
                NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  f_c_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (f_c_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), f_c_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (f_c_button, GTK_CAN_DEFAULT);

  f_open_button = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (f_open_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), f_open_button, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (f_open_button, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) f_c_button, "clicked",
                            G_CALLBACK (on_f_c_button_clicked),
                            GTK_OBJECT (f_c_button));
  g_signal_connect_swapped ((gpointer) f_open_button, "clicked",
                            G_CALLBACK (on_f_open_button_clicked),
                            GTK_OBJECT (f_open_button));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, f_c_button, "f_c_button");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, f_open_button, "f_open_button");

  gtk_widget_grab_default (f_open_button);
  return filechooserdialog1;
}

